---
- name: Deploy docker images
  hosts: localhost

  tasks:
    - name: Pull the Docker images specifed in docker-compose
      shell: 
        cmd: docker-compose pull
        chdir: ./
      
    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d --build